version: "3.2"

services:
  permission:
    image: busybox:1.35
    restart: always
    network_mode: bridge
    command: tail -f /etc/hostname
    volumes:
      - ./data/mysql:/data/mysql
      - ./data/redis:/data/redis
    healthcheck:
      interval: 5s
      test: find /data -mindepth 1 -maxdepth 1 ! -perm 777 -exec chmod 777 {} +

  mysql:
    image: bitnami/mysql:8.0
    restart: always
    container_name: local_mysql
    network_mode: bridge
    depends_on:
      permission:
        condition: service_healthy
    expose:
      - 3306
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/bitnami/mysql/data
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: owa
      MYSQL_PASSWORD: aa111111
      MYSQL_DATABASE: owa

  redis:
    image: bitnami/redis:6.2
    restart: always
    container_name: local_redis
    network_mode: bridge
    depends_on:
      permission:
        condition: service_healthy
    expose:
      - 6379
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/bitnami/redis/data
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
      REDIS_PASSWORD: "aa111111"
