version: '3.7'
x-network_mode: &default-network-mode bridge
x-restart: &default-restart always
x-logging: &default-logging
  options:
    max-size: '200k'
    max-file: '1'
  driver: json-file
x-volume: &default-volume
  - './data:/var/lib/mysql'

services:
  mysql:
    image: mysql:8
    container_name: owa_mysql
    env_file: ./mysql.env
    ports:
      - '127.0.0.1:3307:3306'
    volumes: *default-volume
    network_mode: *default-network-mode
    restart: *default-restart
    logging: *default-logging
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
    depends_on:
      - permission

  permission:
    image: busybox:latest
    container_name: owa_mysql_permission
    environment:
      - DATA_PATH=/var/lib/mysql
      - NOTICE=/tmp/notice.txt
    user: root
    command: sh -c 'chmod 777 $${DATA_PATH} && env > $${NOTICE} && tail -f $${NOTICE}'
    network_mode: *default-network-mode
    volumes: *default-volume
    restart: *default-restart
    logging: *default-logging
